# For more information: https://laravel.com/docs/sail
version: '3'
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            #- '${FORWARD_FRONTEND_PORT:-8080}:3004'
            - '3010:3010'
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        networks:
            - sail
        depends_on:
            - backend
    backend:
        container_name: backend
        build:
            context: ./backend/vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                # WWWGROUP: '${WWWGROUP}'
                WWWGROUP: '1000'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            # WWWUSER: '${WWWUSER}'
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './backend:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: reminders
            MYSQL_USER: amir
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - '8083:80'
        networks:
            - sail

    redis:
        container_name: redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]                     
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
